framework:
  workflows:
    !php/const Majerome\WorkshopPlugin\StateMachine\BrandTransitions::GRAPH:
      type: state_machine
      marking_store:
        type: method
        property: state
      supports:
        - Majerome\WorkshopPlugin\Entity\Brand\Brand
      initial_marking: !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_NEW
      places:
        - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_NEW
        - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_APPROVED
        - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_REJECTED
        - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_SUSPENDED
      transitions:
        !php/const Majerome\WorkshopPlugin\StateMachine\BrandTransitions::TRANSITION_APPROVE:
          from:
            - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_NEW
            - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_REJECTED
            - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_SUSPENDED
          to:
            - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_APPROVED
        !php/const Majerome\WorkshopPlugin\StateMachine\BrandTransitions::TRANSITION_REJECT:
          from:
            - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_NEW
          to:
            - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_REJECTED
        !php/const Majerome\WorkshopPlugin\StateMachine\BrandTransitions::TRANSITION_SUSPEND:
          from:
            - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_APPROVED
          to:
            - !php/const Majerome\WorkshopPlugin\Entity\Brand\BrandInterface::STATE_SUSPENDED
