sylius_grid:
  grids:
    sylius_admin_product:
      filters:
        brand:
          type: entity
          form_options:
            class: "%majerome_workshop.model.brand.class%"
            choice_label: name
