majerome.workshop_plugin.admin_brand:
  resource: |
    alias: majerome_workshop.brand
    section: admin
    templates: "@SyliusAdmin\\shared\\crud"
    redirect: update
    except: ['show']
    grid: majerome.workshop_plugin.admin_brand
    vars:
        all:
            templates:
                form: '@MajeromeWorkshopPlugin/Admin/Brand/_form.html.twig'
  type: sylius.resource

majerome.workshop_plugin.admin_brand_show:
  path: /brands/{id}
  methods: [GET]
  defaults:
    _controller: majerome_workshop.controller.brand::showAction
    _sylius:
      template: "@MajeromeWorkshopPlugin/Admin/Brand/show.html.twig"

majerome.workshop_plugin.admin_brand_approve:
  path: /brands/{id}/approve
  methods: [PUT]
  defaults:
    _controller: majerome_workshop.controller.brand::applyStateMachineTransitionAction
    _sylius:
      state_machine:
        graph: sylius_brand
        transition: approve
      redirect: referer

majerome.workshop_plugin.admin_brand_reject:
  path: /brands/{id}/reject
  methods: [PUT]
  defaults:
    _controller: majerome_workshop.controller.brand::applyStateMachineTransitionAction
    _sylius:
      state_machine:
        graph: sylius_brand
        transition: reject
      redirect: referer

majerome.workshop_plugin.admin_brand_suspend:
  path: /brands/{id}/suspend
  methods: [PUT]
  defaults:
    _controller: majerome_workshop.controller.brand::applyStateMachineTransitionAction
    _sylius:
      state_machine:
        graph: sylius_brand
        transition: suspend
      redirect: referer
