majerome.workshop_plugin.shop_branded_products_index:
  path: /branded-products/{code}
  methods: [GET]
  defaults:
    _controller: sylius.controller.product::indexAction
    _sylius:
      template: "@MajeromeWorkshopPlugin/Shop/Product/brandedProducts.html.twig"
      repository:
        method: findBrandedProducts
        arguments:
          - expr:service('majerome_workshop.repository.brand').findOneByCode($code)

majerome.workshop_plugin.shop_partial_branded_products_index:
  path: /_partial/brands
  methods: [GET]
  defaults:
    _controller: majerome_workshop.controller.brand::indexAction
    _sylius:
      template: "@MajeromeWorkshopPlugin/Shop/Brand/_brand.html.twig"
      repository:
        method: findEnabledByChannel
        arguments:
          - expr:service('sylius.context.channel').getChannel()
