imports:
  - { resource: "@MajeromeWorkshopPlugin/config/grids/*.yaml" }
  - { resource: "@MajeromeWorkshopPlugin/config/workflow/*.yaml" }
  - { resource: "@MajeromeWorkshopPlugin/config/fixtures/*.yaml" }
